# Generated by Django 2.1.1 on 2018-10-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='模型名')),
                ('interface', models.CharField(max_length=20, verbose_name='接口名')),
                ('supplier', models.CharField(max_length=20, verbose_name='供应商')),
                ('is_model', models.BooleanField(verbose_name='是否模型')),
            ],
        ),
        migrations.CreateModel(
            name='Qparam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='参数名')),
                ('param', models.CharField(max_length=20, verbose_name='参数字段')),
            ],
        ),
        migrations.AddField(
            model_name='inter',
            name='inter',
            field=models.ManyToManyField(related_name='params', to='polls.Qparam', verbose_name='参数'),
        ),
        migrations.AddField(
            model_name='inter',
            name='rely',
            field=models.ManyToManyField(blank=True, null=True, related_name='_inter_rely_+', to='polls.Inter', verbose_name='依赖接口'),
        ),
    ]
