# Generated by Django 2.1.1 on 2018-10-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inter',
            name='inter',
            field=models.ManyToManyField(to='polls.Qparam', verbose_name='参数'),
        ),
    ]
