# Generated by Django 2.1.1 on 2018-10-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181022_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inter',
            name='interface',
            field=models.CharField(max_length=32, verbose_name='接口名'),
        ),
        migrations.AlterField(
            model_name='inter',
            name='name',
            field=models.CharField(max_length=32, verbose_name='模型名'),
        ),
        migrations.AlterField(
            model_name='inter',
            name='supplier',
            field=models.CharField(max_length=32, verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='qparam',
            name='name',
            field=models.CharField(max_length=32, verbose_name='参数名'),
        ),
        migrations.AlterField(
            model_name='qparam',
            name='param',
            field=models.CharField(max_length=32, verbose_name='参数字段'),
        ),
    ]
